tmux kill-session -t pane_c1_s1
tmux kill-session -t pane_c1_s2
tmux kill-session -t pane_c1_s3
tmux kill-session -t pane_c1_s4
tmux kill-session -t pane_c1_s5
tmux kill-session -t pane_c2_s1
tmux kill-session -t pane_c2_s2
tmux kill-session -t pane_c2_s3
tmux kill-session -t pane_c2_s4
tmux kill-session -t pane_c2_s5
tmux kill-session -t pane_c3_s1
tmux kill-session -t pane_c3_s2

tmux kill-session -t pane_c1_s1_v1
tmux kill-session -t pane_c1_s1_v2
tmux kill-session -t pane_c1_s1_v3
tmux kill-session -t pane_c1_s1_v4
tmux kill-session -t pane_c1_s1_v5
tmux kill-session -t pane_c1_s2_v1
tmux kill-session -t pane_c1_s2_v2
tmux kill-session -t pane_c1_s2_v3
tmux kill-session -t pane_c1_s2_v4
tmux kill-session -t pane_c1_s2_v5
tmux kill-session -t pane_c1_s3_v1
tmux kill-session -t pane_c1_s3_v2
tmux kill-session -t pane_c1_s3_v3
tmux kill-session -t pane_c1_s3_v4
tmux kill-session -t pane_c1_s3_v5
tmux kill-session -t pane_c1_s4_v1
tmux kill-session -t pane_c1_s4_v2
tmux kill-session -t pane_c1_s4_v3
tmux kill-session -t pane_c1_s4_v4
tmux kill-session -t pane_c1_s4_v5
tmux kill-session -t pane_c1_s5_v1
tmux kill-session -t pane_c1_s5_v2
tmux kill-session -t pane_c1_s5_v3
tmux kill-session -t pane_c1_s5_v4
tmux kill-session -t pane_c1_s5_v5
tmux kill-session -t pane_c2_s1_v1
tmux kill-session -t pane_c2_s1_v2
tmux kill-session -t pane_c2_s1_v3
tmux kill-session -t pane_c2_s1_v4
tmux kill-session -t pane_c2_s1_v5
tmux kill-session -t pane_c2_s2_v1
tmux kill-session -t pane_c2_s2_v2
tmux kill-session -t pane_c2_s2_v3
tmux kill-session -t pane_c2_s2_v4
tmux kill-session -t pane_c2_s2_v5
tmux kill-session -t pane_c2_s3_v1
tmux kill-session -t pane_c2_s3_v2
tmux kill-session -t pane_c2_s3_v3
tmux kill-session -t pane_c2_s3_v4
tmux kill-session -t pane_c2_s3_v5
tmux kill-session -t pane_c2_s4_v1
tmux kill-session -t pane_c2_s4_v2
tmux kill-session -t pane_c2_s4_v3
tmux kill-session -t pane_c2_s4_v4
tmux kill-session -t pane_c2_s4_v5
tmux kill-session -t pane_c2_s5_v1
tmux kill-session -t pane_c2_s5_v2
tmux kill-session -t pane_c2_s5_v3
tmux kill-session -t pane_c2_s5_v4
tmux kill-session -t pane_c2_s5_v5
tmux kill-session -t pane_c3_s1_v1
tmux kill-session -t pane_c3_s1_v2
tmux kill-session -t pane_c3_s1_v3
tmux kill-session -t pane_c3_s1_v4
tmux kill-session -t pane_c3_s1_v5
tmux kill-session -t pane_c3_s2_v1
tmux kill-session -t pane_c3_s2_v2
tmux kill-session -t pane_c3_s2_v3
tmux kill-session -t pane_c3_s2_v4
tmux kill-session -t pane_c3_s2_v5
tmux kill-session -t pane_c3_s3_v1
tmux kill-session -t pane_c3_s3_v2
tmux kill-session -t pane_c3_s3_v3
tmux kill-session -t pane_c3_s3_v4
tmux kill-session -t pane_c3_s3_v5
tmux kill-session -t pane_c3_s4_v1
tmux kill-session -t pane_c3_s4_v2
tmux kill-session -t pane_c3_s4_v3
tmux kill-session -t pane_c3_s4_v4
tmux kill-session -t pane_c3_s4_v5
tmux kill-session -t pane_c3_s5_v1
tmux kill-session -t pane_c3_s5_v2
tmux kill-session -t pane_c3_s5_v3
tmux kill-session -t pane_c3_s5_v4
tmux kill-session -t pane_c3_s5_v5


tmux kill-session -t pane_c1_s1_v1_
tmux kill-session -t pane_c1_s1_v2_
tmux kill-session -t pane_c1_s1_v3_
tmux kill-session -t pane_c1_s1_v4_
tmux kill-session -t pane_c1_s1_v5_
tmux kill-session -t pane_c1_s2_v1_
tmux kill-session -t pane_c1_s2_v2_
tmux kill-session -t pane_c1_s2_v3_
tmux kill-session -t pane_c1_s2_v4_
tmux kill-session -t pane_c1_s2_v5_
tmux kill-session -t pane_c1_s3_v1_
tmux kill-session -t pane_c1_s3_v2_
tmux kill-session -t pane_c1_s3_v3_
tmux kill-session -t pane_c1_s3_v4_
tmux kill-session -t pane_c1_s3_v5_
tmux kill-session -t pane_c1_s4_v1_
tmux kill-session -t pane_c1_s4_v2_
tmux kill-session -t pane_c1_s4_v3_
tmux kill-session -t pane_c1_s4_v4_
tmux kill-session -t pane_c1_s4_v5_
tmux kill-session -t pane_c1_s5_v1_
tmux kill-session -t pane_c1_s5_v2_
tmux kill-session -t pane_c1_s5_v3_
tmux kill-session -t pane_c1_s5_v4_
tmux kill-session -t pane_c1_s5_v5_
tmux kill-session -t pane_c2_s1_v1_
tmux kill-session -t pane_c2_s1_v2_
tmux kill-session -t pane_c2_s1_v3_
tmux kill-session -t pane_c2_s1_v4_
tmux kill-session -t pane_c2_s1_v5_
tmux kill-session -t pane_c2_s2_v1_
tmux kill-session -t pane_c2_s2_v2_
tmux kill-session -t pane_c2_s2_v3_
tmux kill-session -t pane_c2_s2_v4_
tmux kill-session -t pane_c2_s2_v5_
tmux kill-session -t pane_c2_s3_v1_
tmux kill-session -t pane_c2_s3_v2_
tmux kill-session -t pane_c2_s3_v3_
tmux kill-session -t pane_c2_s3_v4_
tmux kill-session -t pane_c2_s3_v5_
tmux kill-session -t pane_c2_s4_v1_
tmux kill-session -t pane_c2_s4_v2_
tmux kill-session -t pane_c2_s4_v3_
tmux kill-session -t pane_c2_s4_v4_
tmux kill-session -t pane_c2_s4_v5_
tmux kill-session -t pane_c2_s5_v1_
tmux kill-session -t pane_c2_s5_v2_
tmux kill-session -t pane_c2_s5_v3_
tmux kill-session -t pane_c2_s5_v4_
tmux kill-session -t pane_c2_s5_v5_
tmux kill-session -t pane_c3_s1_v1_
tmux kill-session -t pane_c3_s1_v2_
tmux kill-session -t pane_c3_s1_v3_
tmux kill-session -t pane_c3_s1_v4_
tmux kill-session -t pane_c3_s1_v5_
tmux kill-session -t pane_c3_s2_v1_
tmux kill-session -t pane_c3_s2_v2_
tmux kill-session -t pane_c3_s2_v3_
tmux kill-session -t pane_c3_s2_v4_
tmux kill-session -t pane_c3_s2_v5_
tmux kill-session -t pane_c3_s3_v1_
tmux kill-session -t pane_c3_s3_v2_
tmux kill-session -t pane_c3_s3_v3_
tmux kill-session -t pane_c3_s3_v4_
tmux kill-session -t pane_c3_s3_v5_
tmux kill-session -t pane_c3_s4_v1_
tmux kill-session -t pane_c3_s4_v2_
tmux kill-session -t pane_c3_s4_v3_
tmux kill-session -t pane_c3_s4_v4_
tmux kill-session -t pane_c3_s4_v5_
tmux kill-session -t pane_c3_s5_v1_
tmux kill-session -t pane_c3_s5_v2_
tmux kill-session -t pane_c3_s5_v3_
tmux kill-session -t pane_c3_s5_v4_
tmux kill-session -t pane_c3_s5_v5_